### ISSUE TITLE
Simple Ftp deploy stop working

### ISSUE THREAD

**Issue by urtvs** [HexRx/simple-ftp-deploy#11]
Hi
I use simple ftp deploy for long time but last few days find - that after saving file i did not see in console information about deploy

[Simple FTP Deploy] [Connected 12:56:21]: a.domain.ru:21 (94ms)
[Simple FTP Deploy] [Deployed 12:56:21]: /www/file.php (186ms)

I find this think
1 - if i open file CTRL + P -> search name  open and edit save - all ok
2 - If i make search in Folder -> Thenk open and edit - NOT WORKING

**Comment by HexRx** [comment]
@urtvs hello! Besides not showing anything in the console, did you have any file changes on the FTP server for point 2? Or did the file on FTP have old content?

Also for point 2, after open and edit did you save a file?

**Comment by Aiq0** [comment]
You can set  `"enableDeleteHandler"` option to `false` in global settings (`Preferences -> Package Settings -> Simple FTP Deploy -> Settings - User`) to make it work

Should be fixed with #14
