### ISSUE TITLE
nothing happens

### ISSUE THREAD

**Issue by tjvoll** [HexRx/simple-ftp-deploy#2]
I'm getting no feedback after installing and setting this up in Sublime 3.

My config file is as follows,
{
    "host": "www.myurl.ca",
    "username": "myusername",
    "password": "mypassword,
    "rootDirectory": "/myrootfolder/"
}
No feedback is written to the console when saving a file  :(

**Comment by igor0ser** [comment]
same for me

**Comment by lbriet** [comment]
Same here. Worked on first install though.

NB: think I did update Sublime since installing simple-ftp-deploy.. could be cause?

**Comment by alexandreec** [comment]
same for me

**Comment by ikiK-CRO** [comment]
Yeah nothing for me too. 0 nada...

**Comment by Aiq0** [comment]
It is fixed here: #4. The issue happens only if you were using project, then the root directory was detected incorrectly and the file was not uploaded. It can be closed.
