### ISSUE TITLE
Missing required "on" and/or "file" option(s) in trigger configuration

### ISSUE THREAD

**Issue by ab-tools** [HexRx/simple-ftp-deploy#20]
Hello,

I have a very simple configuration like this:
```
{
    "host": "###",
    "username": "###",
    "triggers": [
        {
            "on": "save",
            "extensions": [".html", ".php", ".css", ".js"]
        }
    ]
}
```

All seems to be working fine and the files I change are also uploaded to the FTP server correctly upon save, but each time I need to confirm an incorrect error message `Missing required "on" and/or "file" option(s) in trigger configuration` popping up whenever I save a file.

Why I get this error message despite I do have an `on` trigger set and all is working correctly?

Best regards and thanks in advance
Andreas

**Comment by Aiq0** [comment]
Hello,

Triggers are for running scripts on save - ie if you want to minify some file before upload. If you only want to upload files on save, you can leave triggers section empty and it will just work. The error message is saying, that "or" and/or "file" are missing (but both are required, as you need to know what and when to run it). Maybe it could have better message...

**Comment by ab-tools** [comment]
First thanks for your very quick reply, Andrej, much appreciated!

Understood now, that was indeed not clear to me that you don't need the whole `triggers` section in my case. Perhaps you could add a note about this in the documentation and/or error message.

But I remove it now and all is working fine.
Really useful extension, thanks a lot for that!

Best regards
Andreas

**Comment by HexRx** [comment]
Hi guys,

@Aiq0 thank you for your prompt response!

@ab-tools I've updated the documentation about `triggers`, hopefully it's clearer now.

**Comment by ab-tools** [comment]
Perfect, thanks both of you again!
